# Generated by Django 3.0.2 on 2020-01-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('preview', models.TextField(max_length=516)),
                ('content', models.TextField(max_length=1024)),
                ('posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
